[package]
name = "xliff-translation"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.3"
lasso = "0.7.3"
quick-xml = { version = "0.39.2", features = ["serde", "serialize"] }
regex = "1.12.3"
serde = "1.0.228"
thiserror = "2.0.18"
tinystr = "0.8.3"
xliff-raw = { version = "0.1.0", path = "../xliff-raw" }
