[package]
name = "xliff-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.10.2" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.10.2" }
clap = { version = "4.6.1", features = ["derive"] }
comfy-table = "7.2.2"
glob = "0.3.3"
inquire = "0.9.4"
llama-rs = "0.17.0"
regex = "1.12.3"
tinystr = "0.8.3"
xliff-translation = { version = "0.1.0", path = "../xliff-translation" }
